### PR TITLE
Fix the manual page installation

### PR DESCRIPTION
**Pull request by 0mp**

### CODE REVIEW

**Comment by csjayp** [comment]
Merged and tag for 1.0.2 pushed. Thanks!

**Comment by dbaio** [comment]
@csjayp Please, update the tag v.1.0.2 to the last commit.

**Comment by csjayp** [comment]
OK -- sorry about that. Should be good.

**Comment by dbaio** [comment]
Still linking to https://github.com/csjayp/setaudit/commit/d4f0aa30b13edbe7aebd4d588b67ded2b4293d97
https://github.com/csjayp/setaudit/releases
I don't know if it's possible to change this...

**Comment by csjayp** [comment]
@dbaio I just re-tagged v1.0.3. This should fix it

**Pull request merged**
